services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    volumes:
      - .:/app
    networks:
      - dev
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dev
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev
  test-api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "19191:9191"
    volumes:
      - .:/app
    networks:
      - test
  test-redis:
    image: redis:7
    ports:
      - "16379:6379"
    volumes:
      - test-redis-data:/data
    networks:
      test:
        aliases:
          - redis
  test-postgres:
    image: postgres:17
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - test-postgres-data:/var/lib/postgresql/data
    networks:
      test:
        aliases:
          - postgres
volumes:
  postgres-data:
  test-postgres-data:
  redis-data:
  test-redis-data:
networks:
  dev:
  test:
