services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    volumes:
      - .:/app
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  redis-data:
